AdminUser.find_or_initialize_by_email(email: 'ico@admin.com', password: 'password', password_confirmation: 'password').save!
AdminUser.find_or_initialize_by_email(email: 'ivan@admin.com', password: 'password', password_confirmation: 'password').save!

# world_cup_2014 = Tournament.create(name: '2014 FIFA World Cup', start_at: '2014-06-12 00:00:00')
uefa_euro_2016 = Tournament.create(name: 'UEFA Euro 2016', start_at: '2016-06-10 21:00:00')

# groupA = Group.create(name: 'A', tournament_id: world_cup_2014.id)
# groupB = Group.create(name: 'B', tournament_id: world_cup_2014.id)
# groupC = Group.create(name: 'C', tournament_id: world_cup_2014.id)
# groupD = Group.create(name: 'D', tournament_id: world_cup_2014.id)
# groupE = Group.create(name: 'E', tournament_id: world_cup_2014.id)
# groupF = Group.create(name: 'F', tournament_id: world_cup_2014.id)
# groupG = Group.create(name: 'G', tournament_id: world_cup_2014.id)
# groupH = Group.create(name: 'H', tournament_id: world_cup_2014.id)

egroupA = Group.create(name: 'A', tournament_id: uefa_euro_2016.id)
egroupB = Group.create(name: 'B', tournament_id: uefa_euro_2016.id)
egroupC = Group.create(name: 'C', tournament_id: uefa_euro_2016.id)
egroupD = Group.create(name: 'D', tournament_id: uefa_euro_2016.id)
egroupE = Group.create(name: 'E', tournament_id: uefa_euro_2016.id)
egroupF = Group.create(name: 'F', tournament_id: uefa_euro_2016.id)

# ef = Elimination.create(code: 'ef', name: '1/8-Final', tournament_id: world_cup_2014.id)
# qf = Elimination.create(code: 'qf', name: '1/4-Final', tournament_id: world_cup_2014.id)
# sf = Elimination.create(code: 'sf', name: '1/2-Final', tournament_id: world_cup_2014.id)
# l = Elimination.create(code: 'l',   name: '3rd Place', tournament_id: world_cup_2014.id)
# f = Elimination.create(code: 'f',   name: 'Final',     tournament_id: world_cup_2014.id)
# c = Elimination.create(code: 'c',   name: 'Champion',  tournament_id: world_cup_2014.id)

eef = Elimination.create(code: 'ef', name: '1/8-Final', tournament_id: uefa_euro_2016.id)
eqf = Elimination.create(code: 'qf', name: '1/4-Final', tournament_id: uefa_euro_2016.id)
esf = Elimination.create(code: 'sf', name: '1/2-Final', tournament_id: uefa_euro_2016.id)
 el = Elimination.create(code: 'l',   name: '3rd Place', tournament_id: uefa_euro_2016.id)
 ef = Elimination.create(code: 'f',   name: 'Final',     tournament_id: uefa_euro_2016.id)
 ec = Elimination.create(code: 'c',   name: 'Champion',  tournament_id: uefa_euro_2016.id)

# Team.create(name: 'Australia', tournament_id: world_cup_2014.id)
# Team.create(name: 'Iran', tournament_id: world_cup_2014.id)
# Team.create(name: 'Japan', tournament_id: world_cup_2014.id)
# Team.create(name: 'South Korea', tournament_id: world_cup_2014.id)
# Team.create(name: 'Algeria', tournament_id: world_cup_2014.id)
# Team.create(name: 'Cameroon', tournament_id: world_cup_2014.id)
# Team.create(name: 'Ghana', tournament_id: world_cup_2014.id)
# Team.create(name: 'Ivory Coast', tournament_id: world_cup_2014.id)
# Team.create(name: 'Nigeria', tournament_id: world_cup_2014.id)
# Team.create(name: 'Costa Rica', tournament_id: world_cup_2014.id)
# Team.create(name: 'Honduras', tournament_id: world_cup_2014.id)
# Team.create(name: 'Mexico', tournament_id: world_cup_2014.id)
# Team.create(name: 'United States', tournament_id: world_cup_2014.id)
# Team.create(name: 'Argentina', tournament_id: world_cup_2014.id)
# Team.create(name: 'Brazil', tournament_id: world_cup_2014.id)
# Team.create(name: 'Chile', tournament_id: world_cup_2014.id)
# Team.create(name: 'Colombia', tournament_id: world_cup_2014.id)
# Team.create(name: 'Ecuador', tournament_id: world_cup_2014.id)
# Team.create(name: 'Uruguay', tournament_id: world_cup_2014.id)
# Team.create(name: 'Belgium', tournament_id: world_cup_2014.id)
# Team.create(name: 'Bosnia and H', tournament_id: world_cup_2014.id)
# Team.create(name: 'Croatia', tournament_id: world_cup_2014.id)
# Team.create(name: 'England', tournament_id: world_cup_2014.id)
# Team.create(name: 'France', tournament_id: world_cup_2014.id)
# Team.create(name: 'Germany', tournament_id: world_cup_2014.id)
# Team.create(name: 'Greece', tournament_id: world_cup_2014.id)
# Team.create(name: 'Italy', tournament_id: world_cup_2014.id)
# Team.create(name: 'Netherlands', tournament_id: world_cup_2014.id)
# Team.create(name: 'Portugal', tournament_id: world_cup_2014.id)
# Team.create(name: 'Russia', tournament_id: world_cup_2014.id)
# Team.create(name: 'Spain', tournament_id: world_cup_2014.id)
# Team.create(name: 'Switzerland', tournament_id: world_cup_2014.id)

Team.create(name: 'Albania', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Austria', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Belgium', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Croatia', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Czech Republic', tournament_id: uefa_euro_2016.id)
Team.create(name: 'England', tournament_id: uefa_euro_2016.id)
Team.create(name: 'France', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Germany', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Hungary', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Iceland', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Italy', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Northern Ireland', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Poland', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Portugal', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Republic of Ireland', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Romania', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Russia', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Slovakia', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Spain', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Sweden', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Switzerland', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Turkey', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Ukraine', tournament_id: uefa_euro_2016.id)
Team.create(name: 'Wales', tournament_id: uefa_euro_2016.id)
