AdminUser.find_or_initialize_by_email(email: 'ico@admin.com', password: 'password', password_confirmation: 'password').save!
AdminUser.find_or_initialize_by_email(email: 'ivan@admin.com', password: 'password', password_confirmation: 'password').save!

world_cup_2014 = Tournament.find_or_create_by_name(name: '2014 FIFA World Cup', start_at: '2014-06-12 00:00:00')

groupA = Group.find_or_create_by_name('A', tournament_id: world_cup_2014.id)
groupB = Group.find_or_create_by_name('B', tournament_id: world_cup_2014.id)
groupC = Group.find_or_create_by_name('C', tournament_id: world_cup_2014.id)
groupD = Group.find_or_create_by_name('D', tournament_id: world_cup_2014.id)
groupE = Group.find_or_create_by_name('E', tournament_id: world_cup_2014.id)
groupF = Group.find_or_create_by_name('F', tournament_id: world_cup_2014.id)
groupG = Group.find_or_create_by_name('G', tournament_id: world_cup_2014.id)
groupH = Group.find_or_create_by_name('H', tournament_id: world_cup_2014.id)

ef = Elimination.find_or_create_by_code('ef', name: '1/8-Final', tournament_id: world_cup_2014.id)
qf = Elimination.find_or_create_by_code('qf', name: '1/4-Final', tournament_id: world_cup_2014.id)
sf = Elimination.find_or_create_by_code('sf', name: '1/2-Final', tournament_id: world_cup_2014.id)
l = Elimination.find_or_create_by_code('l',   name: '3rd Place', tournament_id: world_cup_2014.id)
f = Elimination.find_or_create_by_code('f',   name: 'Final',     tournament_id: world_cup_2014.id)
c = Elimination.find_or_create_by_code('c',   name: 'Champion',  tournament_id: world_cup_2014.id)

Team.find_or_create_by_name('Australia')
Team.find_or_create_by_name('Iran')
Team.find_or_create_by_name('Japan')
Team.find_or_create_by_name('South Korea')
Team.find_or_create_by_name('Algeria')
Team.find_or_create_by_name('Cameroon')
Team.find_or_create_by_name('Ghana')
Team.find_or_create_by_name('Ivory Coast')
Team.find_or_create_by_name('Nigeria')
Team.find_or_create_by_name('Costa Rica')
Team.find_or_create_by_name('Honduras')
Team.find_or_create_by_name('Mexico')
Team.find_or_create_by_name('United States')
Team.find_or_create_by_name('Argentina')
Team.find_or_create_by_name('Brazil')
Team.find_or_create_by_name('Chile')
Team.find_or_create_by_name('Colombia')
Team.find_or_create_by_name('Ecuador')
Team.find_or_create_by_name('Uruguay')
Team.find_or_create_by_name('Belgium')
Team.find_or_create_by_name('Bosnia and H')
Team.find_or_create_by_name('Croatia')
Team.find_or_create_by_name('England')
Team.find_or_create_by_name('France')
Team.find_or_create_by_name('Germany')
Team.find_or_create_by_name('Greece')
Team.find_or_create_by_name('Italy')
Team.find_or_create_by_name('Netherlands')
Team.find_or_create_by_name('Portugal')
Team.find_or_create_by_name('Russia')
Team.find_or_create_by_name('Spain')
Team.find_or_create_by_name('Switzerland')
